### PR TITLE
Turn off block validation if argument validate is false

### PR DESCRIPTION
**Pull request by asinyagin**
Hey,

What do you think about turning off block validation if validate is false? I use the lib as an emulation of the real network, so I need some flag to disable that validation.

### CODE REVIEW

**Comment by wanderer** [comment]
thank you @asinyagin ! ultimately I would like to remove validation all together and use the iterator like we do in [vm.runBlockchain](https://github.com/ethereum/ethereumjs-vm/blob/master/lib/runBlockchain.js#L18)

**Comment by kumavis** [comment]
@asinyagin what are you working on? would love to see it

**Comment by asinyagin** [comment]
@kumavis it's a web-IDE for ethereum. i work with @romanman, btw. you might've seen it already, we showed it on the conference in NY in august. it's not really public right now, i can PM you a link, if you're interested.

**Comment by kumavis** [comment]
@asinyagin oh i didnt realize! yeah @romanman gave me a preview when i was in the consensys office

**Pull request merged**
